INSERT INTO `agent`(`agent_name`,`agent_hash_id`,`agent_type`,`model`,`mcp_server`,`agent_desc`)
VALUES
('回归工程兜底智能体',crc32('回归工程兜底智能体'),1,'Qwen3','http://127.0.0.1/agent_inner','通用智能体'),
('资本招商兜底智能体',crc32('资本招商兜底智能体'),1,'Qwen3','http://127.0.0.1/agent_inner','通用智能体'),
('链式招商兜底智能体',crc32('链式招商兜底智能体'),1,'Qwen3','http://127.0.0.1/agent_inner','通用智能体'),
('园区招商兜底智能体',crc32('园区招商兜底智能体'),1,'Qwen3','http://127.0.0.1/agent_inner','通用智能体'),
('亲缘招商兜底智能体',crc32('亲缘招商兜底智能体'),1,'Qwen3','http://127.0.0.1/agent_inner','通用智能体'),
('人才招商兜底智能体',crc32('人才招商兜底智能体'),1,'Qwen3','http://127.0.0.1/agent_inner','通用智能体');

INSERT INTO `agent`(`agent_name`,`agent_hash_id`,`agent_type`,`bean_name`,`agent_desc`)
VALUES
('回归 - 校友会名录',crc32('回归 - 校友会名录'),2,'AgentBeanImplement','预置逻辑智能体'),
('回归 - 异地籍贯企业名录',crc32('回归 - 异地籍贯企业名录'),2,'AgentBeanImplement','预置逻辑智能体'),
('回归 - 校友企业名录',crc32('回归 - 校友企业名录'),2,'AgentBeanImplement','预置逻辑智能体'),
('回归 - 商会企业名录',crc32('回归 - 商会企业名录'),2,'AgentBeanImplement','预置逻辑智能体'),
('回归 - 商会名录',crc32('回归 - 商会名录'),2,'AgentBeanImplement','预置逻辑智能体'),
('资本 - 资本招商企业推荐理由',crc32('资本 - 资本招商企业推荐理由'),2,'AgentBeanImplement','预置逻辑智能体'),
('资本 - 早小项目清单',crc32('资本 - 早小项目清单'),2,'AgentBeanImplement','预置逻辑智能体'),
('资本 - 基于资本招商推荐企业',crc32('资本 - 基于资本招商推荐企业'),2,'AgentBeanImplement','预置逻辑智能体'),
('链式 - 关联异地企业名录',crc32('链式 - 关联异地企业名录'),2,'AgentBeanImplement','预置逻辑智能体'),
('链式 - 链式招商企业推荐理由',crc32('链式 - 链式招商企业推荐理由'),2,'AgentBeanImplement','预置逻辑智能体'),
('链式 - 链式智推',crc32('链式 - 链式智推'),2,'AgentBeanImplement','预置逻辑智能体'),
('链式 - 链式企业名录',crc32('链式 - 链式企业名录'),2,'AgentBeanImplement','预置逻辑智能体'),
('企业详情',crc32('企业详情'),2,'AgentBeanImplement','预置逻辑智能体'),
('产业链企业名录',crc32('产业链企业名录'),2,'AgentBeanImplement','预置逻辑智能体'),
('舆情 - 舆情招商企业推荐理由',crc32('舆情 - 舆情招商企业推荐理由'),2,'AgentBeanImplement','预置逻辑智能体'),
('舆情 - 舆情招商推荐目标企业',crc32('舆情 - 舆情招商推荐目标企业'),2,'AgentBeanImplement','预置逻辑智能体'),
('舆情 - 技术突破/投资布局',crc32('舆情 - 技术突破/投资布局'),2,'AgentBeanImplement','预置逻辑智能体'),
('海外 - 中资对海外投资产业情况',crc32('海外 - 中资对海外投资产业情况'),2,'AgentBeanImplement','预置逻辑智能体'),
('海外 - 企业详情',crc32('海外 - 企业详情'),2,'AgentBeanImplement','预置逻辑智能体'),
('海外 - 重点企业分布',crc32('海外 - 重点企业分布'),2,'AgentBeanImplement','预置逻辑智能体'),
('海外 - 年度报告',crc32('海外 - 年度报告'),2,'AgentBeanImplement','预置逻辑智能体'),
('海外 - 重点产业构成',crc32('海外 - 重点产业构成'),2,'AgentBeanImplement','预置逻辑智能体'),
('海外 - 重点产业构造',crc32('海外 - 重点产业构造'),2,'AgentBeanImplement','预置逻辑智能体'),
('海外 - 重点龙头企业名单',crc32('海外 - 重点龙头企业名单'),2,'AgentBeanImplement','预置逻辑智能体'),
('海外 - 产业园区分布情况',crc32('海外 - 产业园区分布情况'),2,'AgentBeanImplement','预置逻辑智能体'),
('海外 - 园区企业清单',crc32('海外 - 园区企业清单'),2,'AgentBeanImplement','预置逻辑智能体'),
('海外 - 产业园简介',crc32('海外 - 产业园简介'),2,'AgentBeanImplement','预置逻辑智能体'),
('海外 - 园区名录',crc32('海外 - 园区名录'),2,'AgentBeanImplement','预置逻辑智能体'),
('海外 - 园区企业清单',crc32('海外 - 园区企业清单'),2,'AgentBeanImplement','预置逻辑智能体'),
('海外 - 企业清单',crc32('海外 - 企业清单'),2,'AgentBeanImplement','预置逻辑智能体'),
('海外 - 园区排行榜',crc32('海外 - 园区排行榜'),2,'AgentBeanImplement','预置逻辑智能体'),
('海外 - 园区推荐理由',crc32('海外 - 园区推荐理由'),2,'AgentBeanImplement','预置逻辑智能体'),
('海外 - 推荐招商园区',crc32('海外 - 推荐招商园区'),2,'AgentBeanImplement','预置逻辑智能体'),
('海外 - 政策查询',crc32('海外 - 政策查询'),2,'AgentBeanImplement','预置逻辑智能体'),
('亲缘 - 企业名录',crc32('亲缘 - 企业名录'),2,'AgentBeanImplement','预置逻辑智能体'),
('亲缘 - 企业推荐理由',crc32('亲缘 - 企业推荐理由'),2,'AgentBeanImplement','预置逻辑智能体'),
('亲缘 - 推荐招商目标企业',crc32('亲缘 - 推荐招商目标企业'),2,'AgentBeanImplement','预置逻辑智能体'),
('亲缘 - 校友企业',crc32('亲缘 - 校友企业'),2,'AgentBeanImplement','预置逻辑智能体'),
('人才 - 人才智推',crc32('人才 - 人才智推'),2,'AgentBeanImplement','预置逻辑智能体'),
('人才 - 人才名录',crc32('人才 - 人才名录'),2,'AgentBeanImplement','预置逻辑智能体'),
('人才 - 推荐理由',crc32('人才 - 推荐理由'),2,'AgentBeanImplement','预置逻辑智能体');
