### 疑似企业搜索
POST {{base_url}}/record/admin/AppEnterpriseIndustryChainSuspected/selectAll
Content-Type: application/json
token: {{token}}

{
  "enterpriseName": "测试企业",
  "industryChainId": 54,
  "pageNum": 1,
  "pageSize": 10
}

### 疑似企业模板
GET {{base_url}}/record/admin/AppEnterpriseIndustryChainSuspected/templateDownload
Content-Type: application/json
token: {{token}}

### 疑似企业导入
POST {{base_url}}/record/admin/AppEnterpriseIndustryChainSuspected/suspectedEnterprise
#Token
Cache-Control: no-cache
#请求类型
Content-Type: multipart/form-data; boundary=WebAppBoundary
token: {{token}}

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="pangu_enterprise.xlsx"
Content-Type: multipart/form-data

< C:\Users\admin\Desktop\pangu_enterprise.xlsx

--WebAppBoundary
Content-Disposition: form-data; name="industryChainId"
Content-Type: multipart/form-data

1

--WebAppBoundary
Content-Disposition: form-data; name="version"
Content-Type: multipart/form-data

CHAIN.1.3
--WebAppBoundary--