CREATE TABLE `record_product_matches_ai_check` (
                                                   `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
                                                   `version` varchar(128) COLLATE utf8mb4_general_ci NOT NULL COMMENT '版本号',
                                                   `chain_id` bigint NOT NULL COMMENT '产业链ID',
                                                   `enterprise_id` varchar(255) COLLATE utf8mb4_general_ci NOT NULL COMMENT '企业id',
                                                   `enterprise_name` varchar(255) COLLATE utf8mb4_general_ci NOT NULL COMMENT '企业名称',
                                                   `enterprise_uni_code` varchar(255) COLLATE utf8mb4_general_ci NOT NULL COMMENT '企业统一社会信用代码',
                                                   `product_id` varchar(255) COLLATE utf8mb4_general_ci NOT NULL COMMENT '产品ID',
                                                   `product_name` varchar(255) COLLATE utf8mb4_general_ci NOT NULL COMMENT '产品名称',
                                                   `product_url` text COLLATE utf8mb4_general_ci COMMENT '产品URL',
                                                   `product_description` text COLLATE utf8mb4_general_ci COMMENT '产品描述',
                                                   `product_purpose` text COLLATE utf8mb4_general_ci COMMENT '产品用途',
                                                   `label_id` bigint NOT NULL COMMENT '标签ID',
                                                   `label_name` varchar(255) COLLATE utf8mb4_general_ci NOT NULL COMMENT '匹配标签名称',
                                                   `matched_score` decimal(5,2) NOT NULL COMMENT '匹配分数',
                                                   `match_reason` varchar(1024) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '匹配理由',
                                                   `knowledge` text COLLATE utf8mb4_general_ci COMMENT '搜索知识结果',
                                                   `check_reason` varchar(1024) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '质检理由',
                                                   `status` tinyint NOT NULL DEFAULT '0' COMMENT '任务执行状态 0 待执行 1执行中 2质检通过 3质检不通过 4 质检失败',
                                                   `deleted` tinyint NOT NULL DEFAULT '0' COMMENT '逻辑删除标志,1:删除 0:未删除',
                                                   `gmt_create` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
                                                   `gmt_modify` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
                                                   `create_by` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '创建者',
                                                   `update_by` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '更新者',
                                                   PRIMARY KEY (`id`),
                                                   KEY `idx_version` (`version`)
) ENGINE=InnoDB AUTO_INCREMENT=19 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='产品AI质检表'

CREATE TABLE `record_product_matches` (
                                          `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
                                          `chain_id` bigint NOT NULL COMMENT '产业链ID',
                                          `enterprise_id` varchar(255) COLLATE utf8mb4_general_ci NOT NULL COMMENT '企业id',
                                          `enterprise_name` varchar(255) COLLATE utf8mb4_general_ci NOT NULL COMMENT '企业名称',
                                          `enterprise_uni_code` varchar(255) COLLATE utf8mb4_general_ci NOT NULL COMMENT '企业统一社会信用代码',
                                          `product_id` varchar(255) COLLATE utf8mb4_general_ci NOT NULL COMMENT '产品ID',
                                          `product_name` varchar(255) COLLATE utf8mb4_general_ci NOT NULL COMMENT '产品名称',
                                          `product_url` text COLLATE utf8mb4_general_ci COMMENT '产品URL',
                                          `product_description` text COLLATE utf8mb4_general_ci COMMENT '产品描述',
                                          `product_purpose` text COLLATE utf8mb4_general_ci COMMENT '产品用途',
                                          `label_id` bigint NOT NULL COMMENT '标签ID',
                                          `label_name` varchar(255) COLLATE utf8mb4_general_ci NOT NULL COMMENT '匹配标签名称',
                                          `node_id` bigint NOT NULL COMMENT '节点ID',
                                          `node_name` varchar(255) COLLATE utf8mb4_general_ci NOT NULL COMMENT '节点名称',
                                          `matched_score` decimal(5,2) NOT NULL COMMENT '匹配分数',
                                          `match_reason` varchar(1024) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '匹配理由',
                                          `check_reason` varchar(1024) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '质检理由',
                                          `deleted` tinyint NOT NULL DEFAULT '0' COMMENT '逻辑删除标志,1:删除 0:未删除',
                                          `gmt_create` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
                                          `gmt_modify` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
                                          `create_by` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '创建者',
                                          `update_by` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '更新者',
                                          PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='产品结果表'

CREATE TABLE `record_ai_check_record` (
                                          `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
                                          `version` varchar(128) COLLATE utf8mb4_general_ci NOT NULL,
                                          `chain_id` bigint NOT NULL,
                                          `chain_name` varchar(128) COLLATE utf8mb4_general_ci NOT NULL COMMENT '产业链名称',
                                          `status` tinyint NOT NULL DEFAULT '0',
                                          `status_desc` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '状态备注',
                                          `deleted` tinyint NOT NULL DEFAULT '0' COMMENT '逻辑删除标志,1:删除 0:未删除',
                                          `complete_data` datetime DEFAULT NULL COMMENT '完成时间',
                                          `gmt_create` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
                                          `gmt_modify` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
                                          `create_by` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '创建者',
                                          `update_by` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '更新者',
                                          PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='产品AI质检记录表'

